### ISSUE TITLE
Templating with Variables

### ISSUE THREAD

**Issue by jwierzbo** [valiton/grafana-mongodb-atlas-datasource#25]
How to create Variables queries to get e.g. list of available Clusters?

![image](https://user-images.githubusercontent.com/2726393/95359823-dc74f300-08ca-11eb-8c4b-526287c07b4f.png)

**Comment by CapChrisCap** [comment]
Hey @jwierzbo, 
thank you for your question. Honestly, we do not have tested this feature yet because it was not yet on our road map. Therefore, we can not help with this issue directly. I am pretty sure that there needs to be a few code adaptions to support variables but currently, we do not have to implement that. 

However, we would be happy about a pull request. Maybe this documentation would help to get started if you could support us implementing this feature: https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/

Cheers, 
Christoph

**Comment by CapChrisCap** [comment]
Closed because of inactivity. Please re-open again if required.
