### ISSUE TITLE
Support for wildcard

### ISSUE THREAD

**Issue by jorkzijlstra** [valiton/grafana-mongodb-atlas-datasource#34]
I currently need to spell out a separate query for each of the nodes in the cluster.

It would be nice if it would be possible to add a wildcard option for the atlas node name in the Dimension. It does already work for the metrics part (test * in the screenshot)

Something like:
![image](https://user-images.githubusercontent.com/15804835/108261972-9bd49280-7164-11eb-9da3-44a317799e3b.png)

**Comment by CapChrisCap** [comment]
Hello @jorkzijlstra , 
thanks for the feature request. Unfortunately, this is not that easy because MongoDB Atlas does not provide an aggregated metric for that. Calculating this within Grafana would be a high overhead. I would rather recommend using the [MetaQueries datasource](https://grafana.com/grafana/plugins/goshposh-metaqueries-datasource) to aggregate queries (or the pre-build Grafana Aggregations). This is e.g. how it looks with the Grafana Metaquery plugin (only with another DS, but our plugin can be also used): 
![](https://raw.githubusercontent.com/GoshPosh/grafana-meta-queries/master/img/arithmetic-ex2.png?raw=true)
Source: https://grafana.com/grafana/plugins/goshposh-metaqueries-datasource

I will close this issue for now because this is not something where we can further improve unfortunately. If there are any questions left, re-open this issue.

**Comment by jorkzijlstra** [comment]
Thanks for the explanation. Ill have a look into the metaqueries or just use it as is.
