### ISSUE TITLE
All Mongo Metrics aren't populated

### ISSUE THREAD

**Issue by aslamkhan-dremio** [valiton/grafana-mongodb-atlas-datasource#47]
**All Mongo Metrics aren't populated**
All Metrics exposed by mongo arent available after I installed your rc3 plugin. https://docs.atlas.mongodb.com/reference/alert-conditions/#std-label-alert-conditions

EX: Host has index suggestions¶
Replication Lag

**Expected behavior**
I should see all metrics

**Comment by CapChrisCap** [comment]
Hey @aslamkhan-dremio , 
thank you for testing our rc and providing feedback, we really appreciate this!  :) 

I think I can not reproduce your issue. Are you referring to the process dimensions that were introduced with this commit? 
https://github.com/valiton/grafana-mongodb-atlas-datasource/commit/80ad100d3557213ce06b2b28bb6b3d13cb310a51

When testing the selection, I am able to select them as previously: 
![image](https://user-images.githubusercontent.com/8481503/125617236-ee08a89e-e6e5-4cbc-a609-478c74084596.png)

Can you provide more details on the issue so that we can reproduce it better? 

Thank you! :)

**Comment by aslamkhan-dremio** [comment]
I think they are different from 
`Replication Oplog Window
Replication Lag
Replication Headroom`

Also, I dont see 
`Host has index suggestions`

Can you check list of metrics from here: https://docs.atlas.mongodb.com/reference/alert-conditions/#std-label-alert-conditions

**Comment by CapChrisCap** [comment]
As I understand you @aslamkhan-dremio, you want to reproduce the alerting behaviour in Grafana in the same way as you can do this in Atlas, is this correct? 

If yes, then MongoDB Atlas sometimes provides more dimensions because it sometimes already pre-aggregates some metrics for a better alerting functionality. What we provide is the [base dimensions of MongoDB Atlas](https://docs.atlas.mongodb.com/reference/api/process-measurements/#measurement-values). With this list, you can reproduce different alert settings, as e.g. shown for the Host has index suggestions" alert: 

> If the [query targeting ratio](https://docs.atlas.mongodb.com/reference/alert-resolutions/query-targeting/#std-label-query-targeting-resolution) for a host consistently exceeds 10,000 for a period of 10 minutes, Performance Advisor checks the host for inefficient queries and possible indexes to improve performance. If Performance Advisor determines that the host would benefit from one or more indexes, this alert triggers and directs you to create the suggested indexes.

However, you told that within the previous version, you could set your needed dimensions. Can you give an example for this (e.g. with a screenshot)? Then we can check whether we missed some in the upcoming version :-)

**Comment by CapChrisCap** [comment]
closed due to inactivity, feel free to re-open if required
